#custom aliases
alias fv="fzf --bind 'enter:become(vim {})'"
alias ff="fzf --height 40%"
alias la="lsd -A"
alias lsa="lsd -la"
alias ca="batcat "
alias bi="brew install "
alias v="vim "
alias nv="nvim "
alias find="fd"
alias gp="git push "
alias s="sudo "
