
# Enable mouse support
set -g mouse on

# Set prefix
# Use your login shell as default

set -g default-shell /home/linuxbrew/.linuxbrew/bin/zsh 

set -g assume-paste-time 0
set -ga terminal-features ",xterm-256color:RGB"
set -g default-terminal "tmux-256color"
# capichinp style
set -g status-style bg=#1e1e2e,fg=#cdd6f4
# TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
#
# Unbind default prefix
unbind C-b

# Set new prefix
set -g prefix C-a

# Allow sending prefix to nested tmux
bind C-a send-prefix

# Start window numbering from 1
set -g base-index 1

# Start pane numbering from 1 (optional but recommended)
set -g pane-base-index 1

set -g renumber-windows on

# Initialize TPM (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

