require("user.launch")
require("user.keymaps")
require("user.options")
require("user.autocmds")
spec ("user.colorscheme")
spec ("user.devicons")
spec ("user.treesitter")
spec ("user.mason")
spec ("user.schemastore")
spec ("user.lspconfig")
spec ("user.cmp")
spec ("user.telescope")
spec ("user.none-ls")
spec ("user.whichkey")
-- spec ("user.gitsigns")
spec ("user.nvimtree")
spec ("user.comment")
spec ("user.lualine")
-- spec ("user.navic")
-- spec ("user.breadcrumbs")
spec ("user.harpoon")
spec ("user.autopairs")
spec ("user.neogit")
spec ("user.alpha")
spec ("user.project")
-- spec ("user.indentline")
spec ("user.toggleterm")
-- spec ("user.textobjects")
-- spec ("user.masonlspconfig")
spec ("user.extras.tabnine")
spec ("user.extras.oil")
spec ("user.extras.lab")
spec ("user.extras.colorizer")
spec ("user.extras.dressing")
spec ("user.extras.fidget")
spec ("user.extras.bqf")
require("user.lazy")

